Repository learneda/labs11_learned_a-FE, pull requests merged in 2019-04, with the labels that each got.

#63 🍉 Add rel='noopener noreferrer' to remove warning messages in console
  src/pages/Home.js
Labels: Status: Ready

#69 🥑 Add authentication redirect HOC's
  src/App.js
  src/components/Navbar.js
  src/components/authentication/Auth.js
  src/components/authentication/homeRedirect.js
  src/components/authentication/indexRedirect.js
Labels: Status: Merged

#78 Sam liked post reducer
  src/reducers/index.js
  src/reducers/likedPostReducer.js
Labels: Status: Merged

#84 🍋Update Navbar component & Add DummySearch component
  src/components/DummySearch.js
  src/components/Navbar.js
Labels: Status: Merged

#86 Update Navbar component (minor styling changes)
  src/components/DummySearch.js
  src/components/Navbar.js
  src/components/Toggle.js
Labels: Status: Ready

#92 🍳 Update Navbar styling to be sticky to the top of window
  src/components/DummySearch.js
  src/components/Navbar.js
Labels: Status: Merged

#94 🥑 Avocado, thannnkksss
  src/assets/svg/x.svg
  src/components/Alert.js
  src/components/Browse.js
  src/index.js
Labels: Status: Ready

#110 🥝 Add team GitHub and LinkedIn links
  README.md
Labels: Status: Merged

#111 🍉 Update ## Team tab on README.md
  README.md
Labels: Status: Ready

#112 🍭 Add splash image to README.md
  README.md
  src/assets/img/splash.png
Labels: Status: Merged

#115 🥑Add Profile DropDown
  src/assets/svg/logout.svg
  src/assets/svg/settings.svg
  src/components/ProfileDropDown.js
Labels: Status: Merged

#119 corrected response data name convention
  src/pages/Home.js
  src/styles/Auth.css
Labels: Status: In Progress

#121 editProfile component
  src/components/EditUserProfile.js
  src/components/Sidebar.js
Labels: Status: In Progress

#124 🏊🏼‍♂️ swimming through
  src/actions/index.js
  src/components/Bookmarks.js
  src/components/DummySearch.js
  src/components/EditModal.js
  src/components/EditUserProfile.js
  src/pages/Home.js
  src/pages/Landing/Body.js
  src/pages/NoMatch.js
Labels: Status: Ready

#132 🍩 I need some dunkinnn donutss
  src/pages/Landing/Body.js
Labels: Status: Merged

#137 Follow/Unfollow functionality
  src/actions/index.js
  src/actions/types.js
  src/components/Sidebar.js
  src/components/SidebarById.js
  src/reducers/followReducer.js
Labels: Status: In Progress

#140 🥞 I love pancakes
  src/assets/svg/bookmarks-drawing.svg
  src/assets/svg/online-drawing.svg
  src/pages/Landing/Body.js
Labels: Status: Merged

#141 👶🏻 I've abandoned my child
  src/components/Alert.js
Labels: Status: Merged

#142 🚶🏻‍♀️now walk it out
  src/components/Search.js
  src/components/navigation/Navbar.js
Labels: Status: Merged

#144 🧜🏼‍♂️ I'm a merman (added a toggle to the searchBar component)
  src/components/Search.js
  src/components/navigation/Navbar.js
Labels: Status: Merged

#145 💩 It works but not really
  src/actions/index.js
  src/actions/types.js
  src/components/SidebarById.js
  src/reducers/followReducer.js
  src/reducers/index.js
Labels: Status: In Progress

#146 🧞‍♂️I'm a genie in a bottle baby
  src/components/Search.js
Labels: Status: Ready

#160 Connect recommendedFollow data to Redux
  src/actions/index.js
  src/actions/types.js
  src/components/RecommendedFollow.js
  src/reducers/followReducer.js
Labels: Status: In Progress

#161 🧝🏻‍♂️ three rings for the Elven Kings...
  src/components/RecommendedFollow.js
  src/components/Search.js
Labels: Status: In Progress

#166 🤠 Reorganized front-end file structure
  src/App.js
  src/components/navigation/Navbar.js
  src/components/recommended/Like.js
  src/components/recommended/Likes.js
  src/components/sidebar/RecommendedFollow.js
  src/components/sidebar/Sidebar.js
  src/components/sidebar/SidebarById.js
  src/components/utils/AddLinkPortal.js
  src/components/utils/Alert.js
  src/components/utils/EditModal.js
  src/components/utils/MetadataParse.js
  src/components/utils/Search.js
  src/components/utils/Toggle.js
  src/index.js
  src/pages/Browse.js
  src/pages/Home.js
  src/pages/profile/AuthUserProfile.js
  src/pages/profile/Bookmarks.js
  src/pages/profile/ProfileById.js
  src/pages/profile/UserProfile.js
Labels: Status: Merged

#170 Clean up code and styling
  src/components/navigation/Navbar.js
  src/pages/Home.js
  src/pages/profile/AuthUserProfile.js
Labels: Status: In Progress

#180 🍔 Protein style double double pls
  src/components/navigation/Navbar.js
  src/components/search/Search.js
  src/components/search/SearchUsersDropDown.js
  src/components/utils/Search.js
Labels: Status: Ready

#173 Show more comments functionality
  src/components/comments/CommentBox.js
  src/pages/Home.js
Labels: Status: In Progress

#191 Display window to new users how to add posts
  src/assets/svg/bookmark-drawing.svg
  src/assets/svg/love-it-drawing.svg
  src/assets/svg/not-found-drawing.svg
  src/components/recommended/Likes.js
  src/components/utils/HelpScreen.js
  src/components/utils/Toggle.js
  src/pages/Home.js
  src/pages/profile/Bookmarks.js
Labels: Status: In Progress

#194 "No post found" screen for other users
  src/assets/svg/empty-box-drawing.svg
  src/components/recommended/Likes.js
  src/components/utils/screens/HelpScreen.js
  src/components/utils/screens/NoPostScreen.js
  src/pages/Home.js
  src/pages/profile/Bookmarks.js
  src/pages/profile/ProfileById.js
Labels: Status: In Progress

#223 extracts redux store creation from index.js
  .prettierrc
  src/components/search/Search.js
  src/index.js
  src/store.js
Labels: Status: Ready

#232 🍓 Add useInterval custom hook
  src/App.js
  src/components/hooks/useInterval.js
Labels: Status: Merged
